project:
  type: website

website:
  title: "Funathon 2024"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: https://inseefrlab.github.io/funathon2024_slides/
        text: Slides de présentation

format:
  html:
    theme:
      - cosmo
    toc: true



