project:
  type: website

website:
  title: "Funathon 2024"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      - cosmo
    toc: true



