project:
  type: website

website:
  title: "Funathon 2023"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      - cosmo
    css:
      - styles.css
      - assets/fontawesome.css
      - assets/latex-fontsize.css
    toc: true



